### ISSUE TITLE
Deno support?

### ISSUE THREAD

**Issue by lucsoft** [elchininet/isometric#68] opened 2022-04-14 12:20 UTC
deno is a modern typescript/javascript runtime would love to see first party support for this lib

**Comment by lucsoft** [comment] 2022-04-14 14:22
Deno doesn't use node anymore it's a replacement for nodejs

**Comment by elchininet** [comment] 2022-04-14 18:18
Hi @lucsoft,

It doesn‘t matter that Deno doesn‘t use node. When I mentioned the node package it is because it doesn‘t depend on the browser (it uses `jsdom` behind the scenes) so it can be used with any environment non-browser dependant. I did a quick test and it worked, try to reproduce these steps:

1 - Create a `import_map.json` with the next content

```json
{
    "imports": {
       "jsdom": "https://dev.jspm.io/jsdom"
    }
}
```

This is needed becase the node package tries to import `jsdom` so it should be mapped to a URL so Deno can import it properly. Secondly, as Deno expects ESM modules and `jsdom` is a CommonJS module [jspm](https://jspm.org) should be used to transform it.

2 - Create an `index.js` file with the next content:

```javascript
import { IsometricCanvas, IsometricPath, IsometricRectangle, PlaneView } from 'https://unpkg.com/@elchininet/isometric@3.2.0/dist/esm/index.node.js';

const cube = new IsometricCanvas('body', {
    backgroundColor: '#CCC',
    scale: 120
});

const commonProps = {height: 1, width: 1};

const topPiece = new IsometricPath();
const rightPiece = new IsometricRectangle({...commonProps, planeView: PlaneView.FRONT});
const leftPiece = new IsometricRectangle({...commonProps, planeView: PlaneView.SIDE});

topPiece.mt(0, 0, 1).lt(1, 0, 1).lt(1, 1, 1).lt(0, 1, 1);
rightPiece.right = 1;
leftPiece.left = 1;

cube.addChildren(topPiece, rightPiece, leftPiece);

console.log(cube.getElement().outerHTML);
```

3 - Execute the previous file with Deno

```bash
deno run --import-map=import_map.json index.js
```

You can check in the console the next output:

```
<svg viewBox="0 0 640 480" width="640px" height="480px"><rect fill="white" x="0" y="0" width="640px" height="480px"></rect><path fill="white" fill-opacity="1" stroke="black" stroke-dasharray="" stroke-linecap="butt" stroke-linejoin="round" stroke-opacity="1" stroke-width="1" d="M320 239 L320.866025 239.5 L320 240 L319.133975 239.5z"></path><path fill="white" fill-opacity="1" stroke="black" stroke-dasharray="" stroke-linecap="butt" stroke-linejoin="round" stroke-opacity="1" stroke-width="1" d="M320.866025 240.5 L320 241 L320 240 L320.866025 239.5z"></path><path fill="white" fill-opacity="1" stroke="black" stroke-dasharray="" stroke-linecap="butt" stroke-linejoin="round" stroke-opacity="1" stroke-width="1" d="M319.133975 240.5 L320 241 L320 240 L319.133975 239.5z"></path></svg>
```

**Comment by lucsoft** [comment] 2022-04-14 18:30
Thanks for taking your time for writing these simple instructions.
 
The problem is most of these solutions removes typings but i want keep everything under typescript.
Its so great that this lib is written in Typescript and it made no sense not use the benefits of typescript.

The problem is not missing of DOM APIs or something, its just the typescript part

**Comment by elchininet** [comment] 2022-04-14 18:38
Hi @lucsoft,
I don‘t understand well what you are looking for, in theory you can use also the typescript files without compile.
Could you create a repository describing with code what you are looking for so I can understand the issue?
Regards.

**Comment by lucsoft** [comment] 2022-04-14 19:28
@elchininet 
You can't actually because Deno uses Standard Web based import path resolving
because your tsconfig uses `"moduleResolution": "node"`, which is not a standard, i can't use it directly

i made a demo https://github.com/lucsoft/isometric/tree/master/demo/demo_deno how i would use isometric

**Comment by elchininet** [comment] 2022-04-14 19:56
Hi @lucsoft,

What do you mean with _«which is not a standard»_?

[This is](https://www.typescriptlang.org/docs/handbook/module-resolution.html#module-resolution-strategies) what TypeScript recommends.

>Note: **node** module resolution is the most-commonly used in the TypeScript community and is recommended for most projects. If you are having resolution problems with imports and exports in TypeScript, try setting moduleResolution: "node" to see if it fixes the issue.

Changing **moduleResolution** to **classic** or **nodenext** solves your problem?

**Comment by lucsoft** [comment] 2022-04-14 19:59
note really nodenext just adds https imports

it would be "es2015" but thats incompatible with nodejs but would work in the web and with deno

**Comment by elchininet** [comment] 2022-04-14 20:08
`es2015` is not a valid value for `moduleResolution`. Possible values are:

* `node`
* `node12`
* `nodenext`
* `classic`

`classic` is the one that could be used with `ES2015` modules. Do you think that changing `moduleResolution` satisfies what you are looking for?

**Comment by lucsoft** [comment] 2022-04-14 20:16
oh yeah i missread the docs `classic` it is

**Comment by elchininet** [comment] 2022-04-14 20:23
So, changing the `moduleResolution` would solve your problem?
I can try to check if there is no problem changing it to `classic` if it solves your issue, as far as the library compiles it should be OK.

**Comment by lucsoft** [comment] 2022-04-14 20:38
the problem is that classic doesn't work under node.js

i could update my fork a bit and make it completly on deno and provide stuff to publish it for nodejs

**Comment by elchininet** [comment] 2022-04-14 23:15
Yes, if I change it to `classic` the path aliases stop working. The only things that comes to my mind is to use the Deno import map option and create custom imports for each alias.

**Comment by elchininet** [comment] 2022-04-15 09:21
@lucsoft,

I was following [the documentation](https://deno.land/manual/typescript/types#using-the-triple-slash-reference-directive) related to providing types and it can be done with the triple slash reference directive. In this way you can consume the compiled package as any other client and get the benefits of type checking at the same time.

I'll make some refactoring in the package bundling creation and one of them will be including this directive. I'll let you know when it is done.

Regards.

**Comment by elchininet** [comment] 2022-04-15 18:41
Hi @lucsoft,

The last version ([3.2.1](https://www.npmjs.com/package/@elchininet/isometric/v/3.2.1)) contains the change. You can import the library from:

https://cdn.jsdelivr.net/npm/@elchininet/isometric@3.2.1/esm/index.js

And you will notice the directive at the beginning and importing it you will get type checking with Deno:

![image](https://user-images.githubusercontent.com/3728220/163608494-4e00f090-a154-4b79-a2f6-6d90c76045ca.png)

<img width="496" alt="image" src="https://user-images.githubusercontent.com/3728220/163608203-a5cf532d-27dc-416a-98b1-ec40a3ad4b91.png">

**Comment by lucsoft** [comment] 2022-04-16 12:29
Great thanks could you add this to the readme?

**Comment by elchininet** [comment] 2022-04-16 19:45
Yes, sure, I‘ll add a section about importing the package in Deno.
Regards!

**Comment by elchininet** [comment] 2022-04-17 21:20
Hi @lucsoft,
I‘ve added  [a Deno section](https://github.com/elchininet/isometric#in-deno) on the README.
Closing this issue.
Regards.

**Closed by elchininet** 2022-04-17 21:20 UTC
